### ISSUE TITLE
Toggle keydown on power tap?

### ISSUE THREAD

**Issue by leoj3n** [pkamb/PowerKey#22]
I use BetterTouchTool to bind Hyper+X to open applications, so for instance

`cmd`+`option`+`control`+`shift`+`c` for Chrome
`cmd`+`option`+`control`+`shift`+`f` for Firefox
etc...

I use KeyRemap4MacBook to bind `fn` to "Hyper" (`cmd`+`option`+`control`+`shift`) and it works pretty well until I want to bind on the right side of the keyboard; for instance, `fn`+`o` for Opera. KeyRemap4MacBook has options to remap the power key and one option for "Old ADB Keyboard" that binds it to `fn` but that doesn't work for the MacBook keyboard of course.

My understanding is that pressing and holding the power key + another key isn't possible... So that's what I'm thinking maybe it's possible to "tap" the power key to toggle the Hyper until the next individual key (`o`) is pressed.

Didn't see any issues about toggling on power key tap so hope this issue is justified, ty :+1:

**Comment by leoj3n** [comment]
Still needing this functionality :rotating_light:

**Comment by pkamb** [comment]
Adding a global toggle for a modifier key is a bit beyond the scope of this app, I think. You may be able to extend the app for your purposes, or have a different app that listens for the output of PowerKey (say, the F13 key) and then sets that toggle elsewhere in the system.

In the next version of the app I've enabled modifier keys to work alongside the power key. Maybe that will solve your root problem?

Thanks!
