### ISSUE TITLE
assign another key for power

### ISSUE THREAD

**Issue by bionicerkin** [pkamb/PowerKey#25]
Is it also possible to do the reverse? Like you press any other assigned key to power up the macbook from off. That would be handy as a lot of folk's older macbook pros with the dedicated power button, including mine, is acting up and not work. So we just can't turn on the macbooks because of the defective power button but need to reset by disconnecting the battery. Any help would be greatly appreciated. 
Thanks.

**Comment by pkamb** [comment]
Sorry, it won't be possible for this app to do what you're asking. This app requires OS X to be running; the app wouldn't be able to remap any keys while the computer is off.
