### ISSUE TITLE
OS X Yosemite

### ISSUE THREAD

**Issue by phishfi** [pkamb/PowerKey#26]
pkamb, awesome work on your app, love it! Just out of curiosity, have you looked into building this for OS X Yosemite? I have no idea how to go about doing this myself, and I understand that plenty of developers don't like building for beta releases, but I was just curious whether you were in the works on this or if it was one of those things where you planned on waiting for the final release first.

Thanks!

**Comment by pkamb** [comment]
Closing this ticket now that El Capitan is out. Please open a new ticket if you see any issues in the new OS!
