### ISSUE TITLE
INS as the replacement key

### ISSUE THREAD

**Issue by usa-** [pkamb/PowerKey#28]
I am really missing Insert key from the PC keyboard in Remote Desktop sessions and in virtual machines.

**Comment by pkamb** [comment]
In v1.3 I've added the `Help` key, which seems to be the Mac equivalent of `Insert`. Please let me know if that key works in your situation. Thanks!

**Comment by usa-** [comment]
Holy... cow!!! It works!!! Thank you very much.

**Comment by usa-** [comment]
Ther is some problem. When pressed with Shift key, it generates:
1) Shift + Ins
2) Shift + (Key code 231 decimal)

**Comment by pkamb** [comment]
Thanks for the Help/Insert confirmation. We'll cover modifier keys here: 
https://github.com/pkamb/PowerKey/issues/29
