### ISSUE TITLE
Remap Eject key

### ISSUE THREAD

**Issue by omgmog** [pkamb/PowerKey#3]
I've removed the superdrive from my MBP to fit an SSD, so my `eject` key is pretty useless. Can this be modified to support mapping of the `eject` key to forwards delete?

**Comment by pkamb** [comment]
Thanks! The pertinent events for the Eject key are the ones below. Very similar to the power key events.

```
EVENT: type:14 subtype:10, eventData:0, keyCode:0, keyFlags:0, keyState:0, keyRepeat:0
EVENT: type:14 subtype:8, eventData:920064, keyCode:14, keyFlags:2560, keyState:1, keyRepeat:0
EVENT: type:14 subtype:8, eventData:920320, keyCode:14, keyFlags:2816, keyState:0, keyRepeat:0
```

Those work out to have these properties:  

```
Event 1: [type: NSSystemDefined], [subtype: NX_SUBTYPE_EJECT_KEY]
Event 2: [type: NSSystemDefined], [subtype: NX_SUBTYPE_AUX_CONTROL_BUTTONS], [keyCode: NX_POWER_KEY], [keyState: keyDown];
Event 3: [type: NSSystemDefined], [subtype: NX_SUBTYPE_AUX_CONTROL_BUTTONS], [keyCode: NX_POWER_KEY], [keyState: keyUp];
```

I'll be adding support for remapping the Eject key shortly....

**Comment by pkamb** [comment]
I've added eject key remapping support to the `ejectKey` branch, but I don't really have a way to test this myself. If anyone on this thread has a Macbook with an eject key, would you be able to test? Thanks!

This will be released in the next version.
