### ISSUE TITLE
power key interferes with OS X 10.11 shake to find mouse effect

### ISSUE THREAD

**Issue by drcrd** [pkamb/PowerKey#30]
when power key is on the shake to find mouse feature in el capitan does not work.

**Comment by pkamb** [comment]
Hi, thanks for the report. I'll do some investigation.

Please let me know if you hit any issues with El Capitan.

**Comment by drcrd** [comment]
will do thanks

**Comment by JoeDuncko** [comment]
Hi! Any progress with this? I am looking to move to El Capitan but don't want to lose PowerKey.

**Comment by hogash** [comment]
@pkamb Hey Peter, it seems that for me at least, on El Capitan, PowerKey app is not working at all.

Do you have this problem as well? Thanks!

Marius

**Comment by pkamb** [comment]
Hi folks, I've finally upgraded to El Capitan and done some testing.

PowerKey seems to work well out of the box on OS X 10.11. Tapping the power key immediately inputs Forward Delete.

El Cap doesn't have the same issue as Mavericks, where a single tap would sleep the computer. However, a "short hold" of the key **will** sleep. PowerKey is not preventing that. So if you want to use PowerKey, be sure to only use quick taps.

I **am** seeing the original bug report, that the "mouse zoom on shake" feature does not work when PowerKey is running. Will look into what is preventing that.

But overall the app is working correctly. @Marius can you write a report of the behavior you are seeing? @JoeDuncko have you tried the app in 10.11?

Thanks!

**Comment by hogash** [comment]
@pkamb Thanks for having a look Peter!

Strange, not working at all here. I'm guessing you're running 10.11.1 right? 

Also i think this is due to the fact i had previously installed https://github.com/tekezo/Karabiner and https://github.com/tekezo/NoEjectDelay , played with the settings but eventually removed them. They're great but PowerKey was exactly i was looking for.

I'll keep digging, maybe i missed something. Thanks again Peter!

**Comment by marius** [comment]
Nope, I don't use Apple products.

2015-11-06 18:03 GMT+00:00 hogash <notifications@github.com>:

**Comment by pkamb** [comment]
Yes, `10.11.1`

@marius I used the wrong @username, sorry :)

**Comment by JoeDuncko** [comment]
@pkamb Yep! I'm seeing the same thing. Tapping the key forward deletes as it should, holding down the key brings up the sleep prompt as it should. The shake to find mouse feature does not work when PowerKey is on, but that's not that big of a deal. Overall pretty happy with this - PowerKey is something I use constantly, and I would have hated to lose it with the update. Thanks!

**Comment by pkamb** [comment]
This will be fixed in the next version, thanks!

**Comment by drcrd** [comment]
thanks!

**Comment by drcrd** [comment]
thanks. perhaps you could connect with the author of power key to sort out the conflict.

Chris
