### ISSUE TITLE
power key interferes with control + control function in papers 3 citations

### ISSUE THREAD

**Issue by drcrd** [pkamb/PowerKey#32]
If power key is running then the control + control keyboard shortcut for papers 3 (a program for storing and citing references in academic writing) magic citations will not function. You can still use the control + m shortcut in citations if you enable it in papers citation preferences. however if you want to use control + control you need to quit power key and also make sure it does not run at startup then restart the computer.

**Comment by pkamb** [comment]
Hi, thanks for reporting this. What exactly do you mean by `control + control` as a keyboard shortcut? Thanks!

**Comment by drcrd** [comment]
when you have the citations portion of papers 3 running it allows you to call up a function in the program allowing you to insert citations of articles you have stored in your papers program. the keyboard shortcut to call up the citations function is to press control twice (control + control). hopefully that helps.
Cheers
chris

**Comment by pkamb** [comment]
I tested out this Papers app and I'm not quite sure what's going on. I had it working with PowerKey, but at some point the `Ctrl + Ctrl` shortcut stops working. Quitting PowerKey and/or Papers does not cause the keyboard shortcut to start up again without restarting your Mac.

The `Ctrl + M` keyboard shortcut does seem to work fine, so I might suggest switching to that keyboard shortcut instead. 

![Papers citations keyboard shortcuts](https://cloud.githubusercontent.com/assets/342355/11316522/4b565960-8fbf-11e5-9647-4b099476c3dc.png)

You might also try contacting the developers of Papers. If they could chime in with the method that they are using to install this shortcut, we could perhaps make the apps play better together.

**Comment by drcrd** [comment]
peter,
thanks. i sent info to papers team. hopefully they will respond. right the control m works.
cheers
chris
