### ISSUE TITLE
Volume Up key

### ISSUE THREAD

**Issue by y0shiy0shi** [pkamb/PowerKey#34]
Any chance you can add in a VolumeUp event line to your code to replace the power key? I'm able to add in F12, which works, but can't get the volume up to work. Is this easier to do with applescript? Finally upgrading to ElCap and it's causing the biggest headaches. Thanks.

**Comment by pkamb** [comment]
Yes, this is probably something best suited to AppleScript:
http://superuser.com/questions/224264/how-do-i-control-the-system-volume-on-os-x-with-a-keyboard-without-media-control

What issues are you hitting in OS X 10.11 El Capitan?

**Comment by y0shiy0shi** [comment]
I was using powerkey alongside keyremap in Yosemite to use key modifiers to
change the power key's behavior based on if I was in a VM or not. Karabiner
removed recognizing the power button completely and now I need to alter
powerkey to do all the work.

In Mac OS: the powerkey is the volume up and hitting fn-power sends an f12

When a VM is active: the powerkey is the F12 and fn-power sends a volume up

Karabiner would then alter the f12/volup button to be a delete key (for
faster response than the power button).

I'll take a look at your link and see if I can replicate. Thanks.
