### ISSUE TITLE
Using VMware Fusion Delete is continuous

### ISSUE THREAD

**Issue by Ramoe69** [pkamb/PowerKey#37]
I am using windows 7 using VMware fusion which is why I wanted to buy Powerkey,

I have just bought it and it works immediately in Mac but when I press the power key once in the virtual machine it deletes continuously as if I have held the delete key down on a normal PC

Anyone had this issue or have any ideas to solve it?

I am running Windows 7 Ultimate on VMware Fusion Professional v7 0 0

**Comment by pkamb** [comment]
There appear to be some known key-repeat issues with VMware, even without the use of PowerKey:

https://communities.vmware.com/thread/450571

http://stackoverflow.com/questions/9313915/why-is-vmware-workstation-adding-keystokes-when-i-type

https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=196

Are you having the same key repeat issues with other keys, or is it only the power/delete key?

Does the power/delete key ever work correctly (one keypress) in the VM, or is it always repeated?

Thanks!

**Comment by pkamb** [comment]
Closing this issue... please reopen or send me an email if you continue to experience this issue.
