### ISSUE TITLE
Power settings menu is activated when using...

### ISSUE THREAD

**Issue by Rediwed** [pkamb/PowerKey#38]
When using a applescript to execute the following command "pmset displaysleepnow" the power settings menu always comes on as well. I've noticed that it ONLY does this when using that specific terminal command.

Is there anyway you can add a Sleep Display feature to the standard functions?

Thanks!

**Comment by pkamb** [comment]
I've noticed that running an AppleScript does bring up the `Are you sure you want to shut down your computer now?` menu, but *only* the first time the script is run. I can't figure out why that is occurring.

Is that what you're seeing as well, the menu only on the first time running the script? Sorry I don't have a better answer, but it may be you'll need to trigger the script once to get rid of the menu. Your script will run immediately thereafter.
