### ISSUE TITLE
Add to brew cask

### ISSUE THREAD

**Issue by alice0meta** [pkamb/PowerKey#40]
I'd like to be able to install this with `brew cask install powerkey`: https://caskroom.github.io/

**Comment by pkamb** [comment]
Thanks. I would accept a PR with the [needed files/setup for brew cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) but adding it myself isn't a top priority at this time.

Please reopen if someone wants to do it!

**Comment by alice0meta** [comment]
I'd try but it seems like this is pretty difficult now; my impression is that it would have been easier with an earlier version like https://github.com/pkamb/PowerKey/blob/dd2dc759c9d55aff76cf56b68f41c87148c42157/README.md where “release versions of PowerKey.app can be found on GitHub”

**Comment by pkamb** [comment]
Yeah, I'll have to tweak my release setup a bit with this. I'd be up for making a non-code signed version available for cask.
