### ISSUE TITLE
PowerKey for old Macs

### ISSUE THREAD

**Issue by devM4x** [pkamb/PowerKey#41]
Hi i have macbook 2009/2010 year (both) they have eject button not power button. So i want replace this eject button with power button, how i can do this? for example i will replace my superDrive with hdd and i don't need no more this button same time i want move off my mac outside from table and not go anytime to power it on.

Sorry for my english...

**Comment by pkamb** [comment]
Don't all Macs with an Eject Key *also* have a metal Power Button on the chassis? Can't you use that instead?

This PowerKey app does work with Eject Keys and Chassis Power Buttons as well, btw. You can use your Eject Key for a function like Forward Delete.

But it's a bit outside the scope of the project to emulate a Power Key when your Eject Key is pressed.
