### ISSUE TITLE
Macbook 2012 not recognizing Powerkey

### ISSUE THREAD

**Issue by luciathomas217** [pkamb/PowerKey#43]
Hello, 
My silver power button (not within keyboard) no longer functions. 
I bought powerkey in order to remap, but the app is somehow not being recognized, or my computer does not respond. I downloaded the powerkey app, and set the powerkey to various keys - escape, tab, f13. none respond. I have tried with caps pressed and not. 
Is there something I need to do differently? 
Thank you!

**Comment by pkamb** [comment]
If the power button no longer functions normally, I would assume that the button hardware is at fault here and is no longer generating the key events that PowerKey relies on to re-map the PowerKey to a secondary function like Forward Delete.

Note that the PowerKey app *does not* re-map a different key such as F13 to behave as is you pressed the power key. It works the other way, remapping the Power Key to work as a more useful command.

Sorry for the confusion! If you contact me through Gumroad we can discuss further privately.
