### ISSUE TITLE
Inconsistent and erratic

### ISSUE THREAD

**Issue by edhendel** [pkamb/PowerKey#44]
I purchased PowerKey a few minutes ago, and it doesn't work very well.  It only works about half the time I press it.  Also, when I press the key multiple times in a row, it only works for the first one or two presses.  Sometimes it randomly makes my computer go into Sleep mode.  The behavior is erratic and inconsistent.  I'm using a 2015 MacBook Pro with macOS Sierra.  I have uninstalled PowerKey on Gumroad and I would like to request a refund please.  Thank you.

**Comment by pkamb** [comment]
No problem, I'll send a refund. Thanks.

This issue is covered here:

https://github.com/pkamb/PowerKey/issues/1

https://github.com/pkamb/PowerKey#pressing-the-power-key-doesnt-always-work

Pressing the Power key doesn't always work.

 > Apple has made mode-switching keys such as Caps-Lock and Power somewhat harder to accidentally press. 

 > You must firmly press the key for half-a-tick longer than a normal keypress for it to be recognized.
