### ISSUE TITLE
PowerKey and the MacBook Pro Touch Bar

### ISSUE THREAD

**Issue by pkamb** [pkamb/PowerKey#48]
On Apple's latests MacBook Pro notebooks, the Touch Bar replaces all keys on the function row, including the Escape key and Power key.

Source: https://512pixels.net/2016/10/magic-toolbar-sierra-leak/

![applepaysplashsa_geo](https://cloud.githubusercontent.com/assets/342355/19702650/6d412b3e-9ab5-11e6-9ebd-f31deb1d2063.png)

Opening this issue to discuss usage of and/or alternatives to [PowerKey](https://github.com/pkamb/PowerKey) on new Apple laptops with the Magic Toolbar.

**Comment by jdlien** [comment]
I bought PowerKey on a lark hoping that it might work with the TouchID "Power" button, but unfortunately that doesn't seem to be the case. Note that a triple-click of this button brings up accessibility options, so clearly the system is aware of presses to the button in some capacity.

In iOS, tools like @rpetrich's Activator could do things like perform different actions based on which finger touched the sensor, so perhaps an intrepid hacker could do quite a bit with the MacBook Pro TouchID sensor. I'm hoping that PowerKey or some similar utility could get a eventually get a click on TouchID to function as Forward Delete or the like.

**Comment by jdlien** [comment]
I have submitted a pull request for my fork of PowerKey that adds support for the TouchID button on TouchBar MacBook Pros. It works consistently, but there is a delay before the release of the key registers. Also, my version will catch the triple click on TouchID, which normally triggers an Accessibility Options dialog, and map that to the chosen command (eg Forward Delete).

Double clicks do not register.

I'd like to know if there's a way to eliminate the delay in the key release registering.

**Comment by pkamb** [comment]
https://github.com/pkamb/PowerKey/pull/54

**Comment by pkamb** [comment]
Added in v1.6 via PR #60
