### ISSUE TITLE
Power on Power off -  Twelve South BookArc

### ISSUE THREAD

**Issue by Gosau** [pkamb/PowerKey#50]
Hy, I have an macBook Pro which is in a BookArc connected to a LG-display and an external keyboard. So the MBP is closed. Can i use this PowerKey ON my external keyboard for powering on/off the MBP?
Best regrards,
Gunther
Greetings from Vienna, Austria - sorry for my bad english. #

**Comment by pkamb** [comment]
Hello, this functionality isn't in PowerKey by default. The app remaps your PowerKey, it doesn't remap other keys to function as Power.

However, you *could* write an Apple Script that servers to reboot or shut down your Mac. You could then trigger this script via PowerKey app (or a different key via a different hotkey mechanism).

That will not work to turn the computer **on**, however. Other than pressing the power button, the only solution I can think of is a schedule as described here: https://www.techwalls.com/power-on-macbook-closed-lid-clamshell-mode/
