### ISSUE TITLE
Arbitrary key to be power button

### ISSUE THREAD

**Issue by lucasrodes** [pkamb/PowerKey#52]
Hey,
The keyboard of my macbook pro 13" 2011 is not working 100%. In particular only specific keys work (Letter W for instance). The power button does not work.
Thus, I would like to set this key to power on/of button. Isn't there anyway to set an arbitrary key to the power button?

Thanks

**Comment by pkamb** [comment]
Hello, this functionality isn't in PowerKey by default. The app remaps your PowerKey, it doesn't remap other keys to function as Power.

However, you *could* write an Apple Script that servers to reboot or shut down your Mac. You could then trigger this script via PowerKey app (or a different key via a different hotkey mechanism).

That will not work to turn the computer **on**, however. Other than pressing the power button, the only solution I can think of is a schedule as described here: https://www.techwalls.com/power-on-macbook-closed-lid-clamshell-mode/
