### ISSUE TITLE
map key to "Lock Screen"

### ISSUE THREAD

**Issue by Kyle-Falconer** [pkamb/PowerKey#53]
I would like to be able to lock the screen when I press the eject button. Having a nice keyboard shortcut like Windows users have win+L key combination would be very handy in a corporate environment.

**Comment by pkamb** [comment]
That sounds like an option perfect for the "Run Script" feature in PowerKey

One of the bash or Apple Scripts here will likely work. Create a script, then run it via PowerKey.

http://apple.stackexchange.com/questions/80058/lock-screen-command-one-liner
http://apple.stackexchange.com/questions/135728/using-applescript-to-lock-screen
