### ISSUE TITLE
External keyboard eject key to action

### ISSUE THREAD

**Issue by zachwolf** [pkamb/PowerKey#55]
The latest gen mac bluetooth keyboards come with an eject key. I'd like to map this useless key to the power button - matching the layout of the built in keyboard. Is this possible? I've downloaded the app and tinkered with the settings but as far as I can tell, nothing is happening.

Maybe I'm misunderstanding the readme, but "But PowerKey does work with the Eject key as well, so you're in luck" leads me to believe this is possible.

**Comment by pkamb** [comment]
Sorry I missed this issue.

PowerKey does work with the Eject key (as well as the Power key and Touch ID key). So yes, you can launch a script via the Eject key of your external Apple keyboard. This script can do something like approximate the power key, although that functionality does not come in PowerKey.app out of the box.

Let me now if you have any other questions!
