### ISSUE TITLE
long press eject button

### ISSUE THREAD

**Issue by lucio97** [pkamb/PowerKey#59]
Hi, 
I really love the app, is very useful with an iMac without the odd.
I would like to suggest you to put an option in the setting for the long press (obviously the user must specify is he is using a eject or power button). I think that can be useful that the Mac continue to delete the text while I press the eject button, as the backspace button works. 
thanks for the time
L.

**Comment by pkamb** [comment]
Hello, thanks for using PowerKey and for opening this issue.

Unfortunately, OS X does not treat the power and eject keys the same as other normal keys. That makes us unable to add repeating behavior when you hold the key, and also makes it impossible to completely prevent some of the system's power key behavior (such as a long press shutting down your Mac).

More information in #1
