### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TaniaSilina** [pkamb/PowerKey#64]
I bought the program for my Macbook air and it is working from time to time, not always. What happen???

**Comment by pkamb** [comment]
I assume you're hitting the issue "Quick successive key presses don't get registered", which unfortunately is a factor of the way the Power and Eject keys are controlled by OS X. We have not found a workaround.

https://github.com/pkamb/PowerKey/issues/1

If this is causing you major issues and you can't adapt to the tap timing, please email me via your receipt and I can send a refund. Thanks!
