### ISSUE TITLE
Eject-Key to Command+Backspace (Delete)

### ISSUE THREAD

**Issue by danz54** [pkamb/PowerKey#65]
Hi,
is there a way to map the Eject-Key to Command+Backspace (Delete)?
I would like to have one key to trash my files instead of pressing command+delete...
Thanks =)

**Comment by pkamb** [comment]
Hello, I think this would work best as an Apple Script launched via PowerKey.

http://macscripter.net/viewtopic.php?id=31585

so something like:

`tell application "Finder" to empty with security`
