### ISSUE TITLE
Suitable for iMac?

### ISSUE THREAD

**Issue by To-Be-Fair** [pkamb/PowerKey#69]
Hi, I have purchased PowerKey for my MacBook, it's working sweet thanks. Will the same app work if I install it on my iMac to map the Eject key to FwdDelete?
If so, do I need to purchase it again or can I install it again from the download email link?

**Comment by pkamb** [comment]
Yes, the App will work with an iMac if you have an Apple keyboard with an Eject Key in the top right.

You can install the same app on all of your own personal computers, no need to purchase twice.

**Comment by To-Be-Fair** [comment]
Hi Peter,
Thanks for your reply. Just wanted to let you know I bought the app again for my desktop. Figured it’s an extra thank you for your work.

Brendon



On 25/07/2018, at 7:48 AM, Peter Kamb <notifications@github.com> wrote:

Yes, the App will work with an iMac if you have an Apple keyboard with an Eject Key in the top right.

You can install the same app on all of your own personal computers, no need to purchase twice.
