### ISSUE TITLE
macbook pro 2018

### ISSUE THREAD

**Issue by prko** [pkamb/PowerKey#70]
Thank you for this fantastic tool.

Is it possible to allow that the power button works by tapping?
The power button is used to recognise fingerprint by tapping. Thus, it should be technically possible.
It would be great if this feature is supported.

best,
prko

**Comment by pkamb** [comment]
Hello, the Touch ID button support was added in version 1.6. Have you tried using it? Should work.

Best,
Peter

https://github.com/pkamb/PowerKey/releases/tag/v1.6.0

https://github.com/pkamb/PowerKey/pull/60

**Comment by prko** [comment]
I am using version 1.6. The button must be pressed.
It would be good if the button work by touching.
