### ISSUE TITLE
Appears to be broken for Mojave 10.14.  Easy fix here. 

### ISSUE THREAD

**Issue by tomatolichy** [pkamb/PowerKey#71]
App will stop working for some people after upgrading to MacOS 10.14.0 Mojave.  (App fails to launch).

Fix is to go to System Preferences / Security & Privacy / Privacy tab / Accessibility settings, and re-enable PowerKey in the list of 'Allow the apps below to control your computer.'

**Comment by pkamb** [comment]
Thanks - I added an alert in #83
