### ISSUE TITLE
Remap PowerKey to another key not emulate other keys behaviour 

### ISSUE THREAD

**Issue by cultdata** [pkamb/PowerKey#74]
Hi, 

I purchased the license, is there a way to remap power key behaviour to some other key, not emulating other to power key

For Eg i dont want power key to act as escape, rather i want escape key to act as power, is this possible via this tool ?

**Comment by pkamb** [comment]
> I want Escape key to act as Power, is this possible via this tool?

No, that's not possible via PowerKey. This tool only remaps the power key to a utility key; not the other way around.

I will add this to the readme.

Try out Karabiner Elements for what you need: https://github.com/pqrs-org/Karabiner-Elements

**Comment by cultdata** [comment]
thanks for the update, since i would not be using it, possible to refund $ back into my account, i dont have your email, you can email me with Title: Refund Reverse will send you the details

**Comment by pkamb** [comment]
Please reply to me via the gumroad notification (or post the email or name you used) and I can.
