### ISSUE TITLE
Update to 1.6?

### ISSUE THREAD

**Issue by rrhill** [pkamb/PowerKey#75]
I have a purchased version of Power Key. Version 1.5.2. I see no way to upgrade to 1.6.0

**Comment by pkamb** [comment]
There's no built-in update mechanism, but the new release versions are tagged on Github and also published via Gumroad.

Gumroad sends an email about new updates. Check for **"PowerKey - Now with Touch Bar and TouchID key support"** in your email.

If you purchased the app you can download the new version from that link and drag it to your applications folder, on top of the existing app.
