### ISSUE TITLE
Where is the option menu ?

### ISSUE THREAD

**Issue by Boring-Dave** [pkamb/PowerKey#76]
I used PowerKey very happily in the background on my MacBook Pro until about a year ago it ceased working following an OS update. I came across it again today and thought it would be a well spent $5 to have it working again. So I'v paid my $5, downloaded and extracted it and moved it to my Apps folder and indeed it is working well, my Power key is now functioning as a forward delete key as it used to. 
However, I cannot find how to access the options menu, just in case I should ever wish to assign the key to a different function. Neither left nor right mouse click on the Power Key folder has any apparent effect. Power Key is one of the ticked options under @Allow these programs to control your Mac" in System Preferences. Is there some other place I need to look to access this menu, or some setting I need to change ?

**Comment by pkamb** [comment]
PowerKey doesn't have a Dock icon or a menu bar icon when running.

To open the preferences window again, re-open the application by double clicking it in your Applications folder.

If it's not running, the app will launch. If it is running, re-opening the app will re-open the preferences window.

the code responsible for this is the `applicationShouldHandleReopen:` method of NSApplicationDelegate:

```
- (BOOL)applicationShouldHandleReopen:(NSApplication *)sender hasVisibleWindows:(BOOL)flag {
    [self.preferencesWindowController showWindow:self];
    [[NSApplication sharedApplication] setActivationPolicy:NSApplicationActivationPolicyRegular];
    
    return NO;
}
```
