### ISSUE TITLE
Fn not one of the choices? Can it be?

### ISSUE THREAD

**Issue by dstillinger** [pkamb/PowerKey#77]
I've been looking for a way to add a Function key to the other side of the keyboard. This seemed liked a perfect fit. Bought right away! But after installing (yeah, I should have read more closely) Fn doesn't appear to be an option....

Is there a way to run a script or something to make it happen? If not, can the dev kindly file "use as Fn key" under "suggestions"? :) Thanks!

**Comment by pkamb** [comment]
Modifier keys unfortunately aren't a good fit for PowerKey.

The app has no way to block the "hold down the power key to restart your Mac" action... so if you hold down the key, your Mac is going to restart.

I wish I was able to hold down the key to repeat Forward Delete, but that's not possible either.

So as it stands, modifier keys won't be an option in PowerKey. Sorry!

It's *possible* you could hack something together with an Apple Script + "Sticky Keys" mode-based modifiers: https://apple.stackexchange.com/questions/94175/how-to-enable-sticky-keys-on-a-mac

**Comment by dstillinger** [comment]
Thanks for the reply, @pkamb Even if I don't use PowerKey now, it still seems to be a worthy product to support. :) 

I find it faintly maddening that Apple isn't more cognizant of keyboard layouts and ease of use, given how much effort they put into mobile accessibility features. Function keys and media buttons are both too useful and too often used for them to have such overlap, WITHOUT being able to reach the function key from both sides of the keyboard. Key commands that require two hands seem antithetical to the whole idea of key commands!

So, crazy thought: is it possible to remap a non-media F-key (F5 or F6?) to Fn? I assume PowerKey can't, but do you know of an elegant way to do it?

**Comment by pkamb** [comment]
For more complex key remapping I would recommend the app Karabiner Elements:

https://github.com/pqrs-org/Karabiner-Elements

**Comment by dstillinger** [comment]
Ha, yours that Karabiner were the two I bought / supported! I couldn't get Karabiner to remap the power or eject keys, but it worked to add another "fn" to the middle of the Fkeys. Talk about a trashy hack, but hey. Works! 

Thanks for your help, and for making neat little apps!
