### ISSUE TITLE
Does Powerkey work with an old Mac Pro

### ISSUE THREAD

**Issue by carlca** [pkamb/PowerKey#78]
I have a Mac Pro (early 2009) with a wireless Magic keyboard. By a devious route, I am running macOS 10.14.6. Can I install Powerkey to disable my DVD eject key which is too close to my BackSpace key for comfort! If so, you've got a sale 😉

**Comment by pkamb** [comment]
> ... the app works perfectly on my old Mac Pro for disabling the Eject key with is perilously close to the backspace key. $5 well spent 😉

 > https://twitter.com/carlcaulkett/status/1263760715061571591

Yes, the app does work to disable or remap the eject key. Enjoy!
