### ISSUE TITLE
Does it disable the power key?

### ISSUE THREAD

**Issue by sweetdreams** [pkamb/PowerKey#79]
Does this app disable to power key? After a liquid spill mine keeps getting activated randomly and causes shut downs. Sometimes to popup comes up but sometimes it shuts down without the popup meaning it must not only be clicking it but also holding it.... Any advice and can this app help me? I assume the holding down function cannot be prevented. What about the click part?

**Comment by pkamb** [comment]
It does have an option to disable the power key.

It's really hard to say if the app will help in your case though... it will probably block some of the events, but PowerKey can't block key-hold events. So you may still hit those? Best to try it out and see.
