### ISSUE TITLE
Make Delete Key "Move to Trash" in Finder

### ISSUE THREAD

**Issue by kj1006** [pkamb/PowerKey#80]
I don't want to right click to delete something in Finder. I just want to press the delete key and it be gone! Can the delete key be remapped to do this?

**Comment by pkamb** [comment]
I'd suggest pressing `CMD-Delete` (aka `CMD-Backspace`) to move items to the Trash.

You could configure PowerKey to do it via a Run Script action, maybe. But better IMO to use the default macOS keyboard shortcut.
