### ISSUE TITLE
Forward Delete Key to delete items

### ISSUE THREAD

**Issue by HamzaBeder** [pkamb/PowerKey#82]
Hello, 
I bought and installed Powerkey. When I press the Power Button on my MacBook Pro, it works to delete texts, but I can't delete files by pressing the Power Button like in Window PC when I press the delete Button. 
Im using MacbookPro14,2 2015 with Touch Bar. 
Thanks. 
Beder

**Comment by grisha108** [comment]
the same problem

**Comment by pkamb** [comment]
Hi - the [shortcut to delete a file in Finder](https://apple.stackexchange.com/questions/16042/how-do-i-delete-a-file-from-my-desktop-using-keyboard) on a Mac is `CMD-Delete` aka `CMD-Backspace` to move that file to the Trash.

The Forward Delete key does not delete files in macOS (like it might in Windows). So PowerKey, emulating a Forward Delete key, will not delete them either.

If you use PowerKey remap the Power key to `Delete (backspace)` then use the shortcut `CMD-Power`, the file will be moved to the Trash.

If you want to use the Forward Delete key to delete files, you will need to remap that functionality in macOS. Once you do, PowerKey should work to trigger that re-mapped functionality.
